# Generated by Django 5.0.6 on 2024-05-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_fechas_importantes_fechafinal_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fechas_Recomendadas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.CharField(
                        max_length=100,
                        verbose_name="fecha inicio vacaciones y fecha final",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="vacaciones",
            name="fechaFinal",
            field=models.DateField(verbose_name="fecha fin vacaciones"),
        ),
        migrations.AlterField(
            model_name="vacaciones",
            name="fechaInicio",
            field=models.DateField(verbose_name="fecha inicio vacaciones"),
        ),
    ]
